// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Nav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"sticky top-0 z-50 backdrop-blur\"><nav id=\"nav\" class=\"py-2\"><div class=\"px-8 max-w-screen-2xl m-auto flex justify-between\"><a class=\"\" href=\"/#\"><img src=\"/static/media/images/logo.svg\" width=\"32px\"></a><ul class=\"flex justify-evenly self-center\"><li class=\"ml-4\"><a href=\"/#\" class=\"text-sm md:text-xl font-normal\">link_1</a></li><li class=\"ml-4\"><a href=\"/link_2\" class=\"text-sm md:text-xl font-normal\">link_2</a></li><li class=\"ml-4\"><a href=\"/link_3\" class=\"text-sm md:text-xl font-normal\">link_3</a></li></ul></div></nav><hr></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
