root = "."
tmp_dir = ".air"

[build]
cmd = "go build -o ./bin/main ."
include_ext = ["go", "templ", "html", "css"]
exclude_dir = ["assets", "tmp", "testdata", "vendor", "web/node_modules"]
log = "air.log"

[log]
time = false
main_only = false
